version: '3.1'

services:
  fiftech-staging:
    container_name: fiftech-staging
    hostname: fiftech-staging
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - IMG=14
        - LOCATION=fiftech-staging
    restart: always
    user: root:root
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - COMPOSE_PROJECT_NAME=fiftech-staging
    ports:
      - ${PORT}:${PORT}
